services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ./backend/.env
    environment:
      NODE_ENV: production
      PORT: 5000
    depends_on: []
    volumes:
      - uploads-data:/app/uploads
    ports:
      - "5000:5000"   # API'ye hosttan erişim
    expose:
      - "5000"

  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - api
    ports:
      - "80:80"       # Uygulama http://localhost
    restart: unless-stopped

volumes:
  uploads-data:
